### ISSUE TITLE
KeyError:'X'

### ISSUE THREAD

**Issue by Liiii007** [AliYoussef96/BCAW-Tool#13]
Hi, I got an error "KeyError:'X'" when I run auto_test on the homepage.
Here is what the error show:

Traceback (most recent call last):
  File "C:\Users\LiYU\PycharmProjects\pythonProject\CDS\BCAWT_test\BCAWT_test.py", line 4, in <module>
    BCAWT_auto_test.auto_test(path, test_fasta)
  File "C:\Users\LiYU\AppData\Local\Programs\Python\Python38\lib\site-packages\BCAWT\BCAWT_auto_test.py", line 24, in auto_test
    BCAWT.BCAW(main_fasta_file = [file] , save_path= path, Auto=True)
  File "C:\Users\LiYU\AppData\Local\Programs\Python\Python38\lib\site-packages\BCAWT\BCAWT.py", line 238, in BCAW
    df_ATCG["GRAVY"] = GRAVY_AROMO.GRAvy_ARomo(seq_main.seq, genetic_code_, G=True)
  File "C:\Users\LiYU\AppData\Local\Programs\Python\Python38\lib\site-packages\BCAWT\GRAVY_AROMO.py", line 36, in GRAvy_ARomo
    gravy = protein_seq.gravy()
  File "C:\Users\LiYU\AppData\Local\Programs\Python\Python38\lib\site-packages\Bio\SeqUtils\ProtParam.py", line 164, in gravy
    total_gravy = sum(ProtParamData.kd[aa] for aa in self.sequence)
  File "C:\Users\LiYU\AppData\Local\Programs\Python\Python38\lib\site-packages\Bio\SeqUtils\ProtParam.py", line 164, in <genexpr>
    total_gravy = sum(ProtParamData.kd[aa] for aa in self.sequence)
KeyError: 'X'

Could you tell me how to fix it? I'm new to here.

**Comment by webbrain-one** [comment]
Hi there! Thanks for reporting this. I’ve opened a pull request to fix the `KeyError: 'X'` you ran into: https://github.com/AliYoussef96/BCAW-Tool/pull/16

The error happens because Biopython’s GRAVY calculation doesn’t recognize `'X'` (unknown amino acid) in protein sequences. This PR adds handling for non-standard characters so `auto_test` can run smoothly without crashing.

Let me know if you run into any other issues. Thanks again for the detailed report! 🐛✨
